import './style.css';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { STLLoader } from 'three/addons/loaders/STLLoader.js';
import { STLExporter } from 'three/addons/exporters/STLExporter.js';
import { toCreasedNormals } from 'three/addons/utils/BufferGeometryUtils.js';
import {createIcons,ChevronRight,CircleHelp,Plus,Download,SlidersHorizontal,FolderOpen,Upload,Box,CircleCheck,Sparkles,Scissors,Info,ShieldCheck,CircleAlert,Scan,ScanLine,Grid2x2,ArrowDownToLine,Mouse,Layers2,Check,Lightbulb,Printer,ArrowUpRight,X,ArrowRight} from 'lucide';
const icons={ChevronRight,CircleHelp,Plus,Download,SlidersHorizontal,FolderOpen,Upload,Box,CircleCheck,Sparkles,Scissors,Info,ShieldCheck,CircleAlert,Scan,ScanLine,Grid2x2,ArrowDownToLine,Mouse,Layers2,Check,Lightbulb,Printer,ArrowUpRight,X,ArrowRight};
import { zipSync, strToU8 } from 'fflate';

const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const refreshIcons=()=>createIcons({icons,attrs:{'stroke-width':1.7}});
refreshIcons();
const palette=['#bdcec5','#cdb6a4','#b1c2dd','#d8cae0','#d7ceab','#a5c8ca'];
const state={original:null,parts:[],axis:2,appliedAxis:2,planes:[60,120],appliedPlanes:[],name:'Vaso Onda',demo:true,busy:true,dirty:false,selected:-1,wire:false};
let toastTimer;
function toast(message,error=false){const el=$('#toast');el.querySelector('span').textContent=message;el.classList.toggle('error',error);el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),error?8500:4500);}
function loading(on,text='Elaborazione del modello…') {state.busy=on;$('#loading').hidden=!on;$('#loading-text').textContent=text;$('#engine-status').textContent=on?'Elaborazione in corso…':'Motore pronto';updateButtons();}
function updateButtons(){for(const s of ['#apply-cuts','#open-file','#upload-zone','#add-plane','#reset-project','#load-demo']) $(s).disabled=state.busy;$('#add-plane').disabled=state.busy||state.planes.length>=5;$('#export-all').disabled=state.busy||state.dirty||!state.parts.length;$$('[data-download]').forEach(b=>b.disabled=state.busy||state.dirty);$$('[data-axis], .plane-slider, .plane-number, [data-remove]').forEach(b=>b.disabled=state.busy);}
function markDirty(){state.dirty=true;$('#dirty-banner').hidden=false;$('#results-status').textContent='Anteprima da aggiornare';updateButtons();updatePlanes();}
const fmt=n=>new Intl.NumberFormat('it-IT',{maximumFractionDigits:1}).format(n);
const sizeOf=b=>b.max.map((v,i)=>v-b.min[i]);
const dimensions=b=>sizeOf(b).map(fmt).join(' × ');
const num=n=>n.toLocaleString('it-IT');
const escapeHtml=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeName=s=>s.normalize('NFKD').replace(/[^a-zA-Z0-9_-]+/g,'_').slice(0,80)||'modello';
const worker=new Worker(new URL('./geometry.worker.js',import.meta.url),{type:'module'});
let taskId=0;const pending=new Map();
worker.onmessage=({data})=>{const p=pending.get(data.id);if(!p)return;pending.delete(data.id);if(data.error)p.reject(new Error(data.error));else p.resolve(data.result);};
worker.onerror=e=>{for(const p of pending.values())p.reject(new Error('Il motore 3D non è disponibile. Ricarica la pagina e riprova.'));pending.clear();};
function request(type,data={}){return new Promise((resolve,reject)=>{const id=++taskId;pending.set(id,{resolve,reject});worker.postMessage({id,type,...data});});}

// All processing and rendering stay on this device.
const scene=new THREE.Scene();
const container=$('#canvas-container');
const camera=new THREE.PerspectiveCamera(33,1,.1,10000);camera.up.set(0,0,1);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;container.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.maxPolarAngle=Math.PI*.94;controls.minDistance=10;controls.maxDistance=100000;controls.target.set(0,0,100);
scene.add(new THREE.HemisphereLight(0xffffff,0xc2c5cc,2));
const key=new THREE.DirectionalLight(0xfff6ea,3.2);key.position.set(-250,-300,420);scene.add(key);
const fill=new THREE.DirectionalLight(0xe6edff,1.5);fill.position.set(250,120,200);scene.add(fill);
const rim=new THREE.DirectionalLight(0xffffff,2);rim.position.set(0,250,400);scene.add(rim);
const group=new THREE.Group();scene.add(group);const planesGroup=new THREE.Group();scene.add(planesGroup);
let grid;
const shadowCanvas=document.createElement('canvas');shadowCanvas.width=shadowCanvas.height=128;const ctx=shadowCanvas.getContext('2d');const grad=ctx.createRadialGradient(64,64,0,64,64,64);grad.addColorStop(0,'rgba(63,78,99,0.20)');grad.addColorStop(.45,'rgba(63,78,99,0.09)');grad.addColorStop(1,'rgba(63,78,99,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,128,128);
const shadow=new THREE.Mesh(new THREE.PlaneGeometry(1,1),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(shadowCanvas),transparent:true,depthWrite:false}));shadow.position.z=-.3;scene.add(shadow);
const ro=new ResizeObserver(()=>{const {width,height}=container.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();});ro.observe(container);
renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});
function geometryFor(part){let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(part.positions,3));g.setIndex(new THREE.BufferAttribute(part.indices,1));const smooth=toCreasedNormals(g,Math.PI/3);if(smooth!==g)g.dispose();return smooth;}
function disposeGroup(g){while(g.children.length){const child=g.children[0];child.traverse(o=>{o.geometry?.dispose();if(o.material){const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{m.map?.dispose();m.dispose();});}});g.remove(child);}}
function drawParts(){disposeGroup(group);state.parts.forEach((part,i)=>{const mesh=new THREE.Mesh(geometryFor(part),new THREE.MeshStandardMaterial({color:palette[i%palette.length],roughness:.74,metalness:.04,wireframe:state.wire}));mesh.userData.part=i;group.add(mesh);});updateExplosion();updateSelection();}
function setGrid(){if(grid){scene.remove(grid);grid.geometry.dispose();grid.material.dispose();}const d=sizeOf(state.original.bounds);const size=Math.max(...d)*3;grid=new THREE.GridHelper(size,30,0xc4cedd,0xdde3ec);grid.rotation.x=Math.PI/2;grid.position.z=-.6;grid.material.transparent=true;grid.material.opacity=.36;grid.material.depthWrite=false;grid.visible=$('#grid-view').classList.contains('active');scene.add(grid);shadow.scale.set(Math.max(d[0],d[1])*2.1,Math.max(d[0],d[1])*2.1,1);}
function gap(){return $('#explode').checked?Number($('#separation').value):0;}
function updateExplosion(){const axis=state.appliedAxis;group.children.forEach((m,i)=>{m.position.set(0,0,0);m.position.setComponent(axis,(i-(axis===2?0:(state.parts.length-1)/2))*gap());});updatePlanes();}
function fitView(top=false){if(!state.parts.length)return;const bounds=new THREE.Box3().setFromObject(group);const center=bounds.getCenter(new THREE.Vector3());const size=bounds.getSize(new THREE.Vector3());const vfov=camera.fov*Math.PI/180;const hfov=2*Math.atan(Math.tan(vfov/2)*camera.aspect);const distance=Math.max(size.z/2/Math.tan(vfov/2),Math.max(size.x,size.y)/2/Math.tan(hfov/2),size.length()*.75)*(camera.aspect<.8?1.88:1.6);if(camera.aspect<.8)center.z+=size.z*.025;controls.target.copy(center);if(top){camera.position.copy(center).add(new THREE.Vector3(.001,-.001,distance*1.1));$('#camera-label').textContent='Dall’alto';}else{camera.position.copy(center).add(new THREE.Vector3(1,-1.6,.95).normalize().multiplyScalar(distance));$('#camera-label').textContent='Prospettiva';}camera.near=Math.max(.01,distance/1000);camera.far=distance*50;camera.updateProjectionMatrix();controls.update();}
controls.addEventListener('start',()=>$('#camera-label').textContent='Prospettiva');
function textSprite(text){const c=document.createElement('canvas');c.width=256;c.height=64;const ctx=c.getContext('2d');ctx.fillStyle='rgba(247,250,255,0.94)';ctx.beginPath();ctx.roundRect(0,0,256,64,12);ctx.fill();ctx.strokeStyle='#bdcce8';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#859bbf';ctx.font='500 24px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,128,33);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false,toneMapped:false}));return sprite;}
function updatePlanes(){disposeGroup(planesGroup);if(!state.original||!$('#show-planes').checked)return;const b=state.original.bounds,dim=sizeOf(b);const axis=state.axis;const other=[0,1,2].filter(a=>a!==axis);const w=dim[other[0]]*1.42,h=dim[other[1]]*1.28;const max=Math.max(...dim);[...state.planes].sort((a,b)=>a-b).forEach((value,i)=>{const center=new THREE.Vector3(...b.min.map((v,a)=>(v+b.max[a])/2));center.setComponent(axis,value);if(!state.dirty&&axis===state.appliedAxis)center.setComponent(axis,value+(i+.5-(axis===2?0:(state.parts.length-1)/2))*gap());const p=new THREE.Group();const geom=new THREE.PlaneGeometry(w,h);if(axis===0){geom.rotateY(Math.PI/2);geom.rotateX(Math.PI/2);}else if(axis===1)geom.rotateX(Math.PI/2);const face=new THREE.Mesh(geom,new THREE.MeshBasicMaterial({color:0x8facd8,side:THREE.DoubleSide,transparent:true,opacity:.045,depthWrite:false}));p.add(face);const edges=new THREE.EdgesGeometry(geom);const line=new THREE.LineSegments(edges,new THREE.LineDashedMaterial({color:0x93aed6,dashSize:max*.022,gapSize:max*.014,transparent:true,opacity:.56,depthWrite:false}));line.computeLineDistances();p.add(line);p.position.copy(center);const label=textSprite(`${['X','Y','Z'][axis]} · ${fmt(value-b.min[axis])} mm`);label.scale.set(max*.28,max*.07,1);label.position.setComponent(other[0],w*.53);label.position.setComponent(other[1],-h*.38);p.add(label);planesGroup.add(p);});}
function renderPlaneControls(){const b=state.original?.bounds||{min:[-60,-60,0],max:[60,60,180]};const min=b.min[state.axis],len=b.max[state.axis]-min;$('#plane-count').textContent=`${state.planes.length} ${state.planes.length===1?'PIANO':'PIANI'}`;$('#plane-list').innerHTML=state.planes.map((v,i)=>{const local=v-min;return `<div class="plane-item"><div class="plane-item-header"><span class="plane-index">${String(i+1).padStart(2,'0')}</span><span class="plane-name">Piano ${i+1}</span><div class="plane-value"><input class="plane-number" data-plane="${i}" type="number" value="${local.toFixed(1)}" min="${(len*.001).toFixed(3)}" max="${(len*.999).toFixed(3)}" step="0.1" aria-label="Posizione piano ${i+1} in millimetri"><span>mm</span></div><button class="icon-button" data-remove="${i}" title="Rimuovi piano ${i+1}" aria-label="Rimuovi piano ${i+1}"><i data-lucide="x"></i></button></div><input class="plane-slider" data-plane="${i}" type="range" min="${len*.001}" max="${len*.999}" step="${Math.min(.1,len/1000)}" value="${local}" style="--pct:${local/len*100}%" aria-label="Posizione piano ${i+1}"><div class="range-labels"><span>0 mm</span><span>${fmt(len)} mm</span></div></div>`;}).join('');refreshIcons();updateButtons();}
$('#plane-list').addEventListener('input',e=>{if(!e.target.matches('.plane-slider,.plane-number')||state.busy)return;const i=Number(e.target.dataset.plane);const b=state.original.bounds;const len=b.max[state.axis]-b.min[state.axis];const n=Number(e.target.value);if(!Number.isFinite(n))return;state.planes[i]=b.min[state.axis]+Math.min(len*.999,Math.max(len*.001,n));if(e.target.matches('.plane-slider')){$(`.plane-number[data-plane="${i}"]`).value=(state.planes[i]-b.min[state.axis]).toFixed(1);}else $(`.plane-slider[data-plane="${i}"]`).value=state.planes[i]-b.min[state.axis];$(`.plane-slider[data-plane="${i}"]`).style.setProperty('--pct',`${(state.planes[i]-b.min[state.axis])/len*100}%`);markDirty();});
$('#plane-list').addEventListener('change',e=>{if(e.target.matches('.plane-number'))renderPlaneControls();});
$('#plane-list').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b||state.busy)return;state.planes.splice(Number(b.dataset.remove),1);renderPlaneControls();markDirty();});
$$('[data-axis]').forEach(button=>button.addEventListener('click',()=>{if(state.busy||!state.original)return;const old=state.axis;state.axis=Number(button.dataset.axis);if(old===state.axis)return;const b=state.original.bounds;state.planes=state.planes.map(v=>b.min[state.axis]+(v-b.min[old])/(b.max[old]-b.min[old])*(b.max[state.axis]-b.min[state.axis]));$$('[data-axis]').forEach(b=>b.classList.toggle('active',b===button));$('#axis-description').textContent=['Larghezza','Profondità','Verticale'][state.axis];renderPlaneControls();markDirty();}));
$('#add-plane').onclick=()=>{if(state.busy||state.planes.length>=5)return;const b=state.original.bounds;const all=[b.min[state.axis],...state.planes,b.max[state.axis]].sort((a,b)=>a-b);let index=0;for(let i=1;i<all.length-1;i++)if(all[i+1]-all[i]>all[index+1]-all[index])index=i;state.planes.push((all[index]+all[index+1])/2);state.planes.sort((a,b)=>a-b);renderPlaneControls();markDirty();};

const thumbRenderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});thumbRenderer.setSize(150,150);thumbRenderer.setPixelRatio(1);thumbRenderer.toneMapping=THREE.ACESFilmicToneMapping;thumbRenderer.toneMappingExposure=1.35;
function thumbnail(part,color){const s=new THREE.Scene();s.add(new THREE.HemisphereLight(0xffffff,0xbdc4d0,2.8));const l=new THREE.DirectionalLight(0xffffff,3);l.position.set(-3,-4,7);s.add(l);const mesh=new THREE.Mesh(geometryFor(part),new THREE.MeshStandardMaterial({color,roughness:.8}));s.add(mesh);const box=new THREE.Box3().setFromObject(mesh),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());const cam=new THREE.PerspectiveCamera(33,1,.01,100000);cam.up.set(0,0,1);cam.position.copy(center).add(new THREE.Vector3(1,-1.6,1.25).normalize().multiplyScalar(Math.max(...size.toArray())*2.5));cam.lookAt(center);thumbRenderer.render(s,cam);const url=thumbRenderer.domElement.toDataURL('image/png');mesh.geometry.dispose();mesh.material.dispose();return url;}
function renderResults(){const count=state.parts.length;$('#parts-count').textContent=count;$('#export-count').textContent=count;$('#total-parts').textContent=count;$('#results-status').textContent='Pronte per il prossimo passo';$('#parts-list').innerHTML=state.parts.map((p,i)=>`<article class="part-card" data-select="${i}" tabindex="0" role="button" aria-label="Seleziona parte ${i+1}"><div class="part-top"><img class="part-thumbnail" alt="Anteprima parte ${i+1}" src="${thumbnail(p,palette[i%palette.length])}"><div class="part-info"><h3><i style="background:${palette[i%palette.length]}"></i>Parte ${String(i+1).padStart(2,'0')}</h3><p>${dimensions(p.bounds)} mm</p><p class="part-triangles">${num(p.triangles)} triangoli</p></div><button class="part-download" data-download="${i}" title="Scarica parte ${i+1}" aria-label="Scarica parte ${i+1} in STL"><i data-lucide="download"></i></button></div><div class="part-bottom"><span><i data-lucide="circle-check"></i> Solido chiuso</span><b>STL · ${fmt((84+p.triangles*50)/1024)} KB</b></div></article>`).join('');$('.viewport-legend').innerHTML=state.parts.map((p,i)=>`<span><i style="background:${palette[i%palette.length]}"></i>Parte ${String(i+1).padStart(2,'0')}</span>`).join('');$('#triangle-count').textContent=`${num(state.parts.reduce((n,p)=>n+p.triangles,0))} triangoli`;refreshIcons();updateButtons();}
function updateSelection(){group.children.forEach((m,i)=>{m.material.emissive.set(i===state.selected?0x263c6e:0x000000);m.material.emissiveIntensity=.15;});$$('[data-select]').forEach(card=>{const active=Number(card.dataset.select)===state.selected;card.classList.toggle('selected',active);card.setAttribute('aria-pressed',String(active));});}
function selectPart(i){state.selected=state.selected===i?-1:i;updateSelection();}
$('#parts-list').onclick=e=>{const download=e.target.closest('[data-download]');if(download){downloadPart(Number(download.dataset.download));return;}const card=e.target.closest('[data-select]');if(card)selectPart(Number(card.dataset.select));};
$('#parts-list').onkeydown=e=>{if(e.target.matches('[data-select]')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();selectPart(Number(e.target.dataset.select));}};
let pointerDown;renderer.domElement.addEventListener('pointerdown',e=>pointerDown=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!pointerDown||Math.hypot(e.clientX-pointerDown[0],e.clientY-pointerDown[1])>5)return;const r=renderer.domElement.getBoundingClientRect();const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(group.children)[0];if(hit)selectPart(hit.object.userData.part);else{state.selected=-1;updateSelection();}});

async function cut(fit=false){if(!state.original)return;loading(true,'Taglio e chiusura delle superfici…');try{const parts=await request('cut',{axis:state.axis,planes:state.planes});if(!parts.length)throw new Error('Nessuna parte generata. Controlla i piani di taglio.');state.parts=parts;state.appliedAxis=state.axis;state.appliedPlanes=[...state.planes];state.dirty=false;state.selected=-1;$('#dirty-banner').hidden=true;drawParts();renderResults();if(fit)fitView();return true;}catch(e){toast(e.message,true);return false;}finally{loading(false);}}
$('#apply-cuts').onclick=async()=>{if(state.busy)return;if(await cut())toast(`${state.parts.length} parti generate. Le superfici di taglio sono chiuse.`);};
async function loadModel(type,positions=null,file=null){if(state.busy&&state.original)return;loading(true,type==='demo'?'Diamo forma al tuo primo progetto…':'Controllo della mesh STL…');try{const original=await request(type,positions?{positions}:{});state.original=original;state.demo=type==='demo';state.name=file?file.name.replace(/\.stl$/i,''):'Vaso Onda';state.axis=2;state.planes=[original.bounds.max[2]/3,original.bounds.max[2]*2/3];state.dirty=true;$('#file-name').textContent=state.name+'.stl';$('#file-meta').textContent=file?`${fmt(file.size/1024/1024)} MB · ${num(original.triangles)} triangoli`:'Modello dimostrativo';$('#model-size').textContent=dimensions(original.bounds)+' mm';$('#model-title').textContent=state.name;$('#project-title').textContent=state.demo?'Progetto senza titolo':state.name;$('#caption-kind').textContent=state.demo?'MODELLO DEMO':'IL TUO MODELLO';$('#model-subtitle').textContent=state.demo?'Un’unica forma, infinite possibilità.':'Il tuo prossimo progetto inizia qui.';$$('[data-axis]').forEach(b=>b.classList.toggle('active',Number(b.dataset.axis)===2));$('#axis-description').textContent='Verticale';$('#explode').checked=true;$('#separation').disabled=false;$('#separation').value=Math.min(18,Math.round(original.bounds.max[2]*.1));$('#separation-value').textContent=$('#separation').value;setGrid();renderPlaneControls();await cut(true);if(type==='import')toast('Modello importato e diviso in 3 sezioni. Personalizza i tagli.');}catch(e){toast(e.message,true);}finally{loading(false);}}
async function importFile(file){if(!file||state.busy)return;if(!file.name.toLowerCase().endsWith('.stl')){toast('Scegli un file STL binario o ASCII.',true);return;}if(file.size>30*1024*1024){toast('Il limite è 30 MB per file.',true);return;}try{const buffer=await file.arrayBuffer();const geometry=new STLLoader().parse(buffer);const positions=new Float32Array(geometry.attributes.position.array);geometry.dispose();if(positions.length/9>500000){toast('Il modello supera il limite di 500.000 triangoli. Riduci la mesh e riprova.',true);return;}await loadModel('import',positions,file);}catch(e){toast('Impossibile leggere il file STL. Verifica che non sia danneggiato.',true);}}
$('#open-file').onclick=$('#upload-zone').onclick=()=>$('#file-input').click();$('#file-input').onchange=async e=>{await importFile(e.target.files[0]);e.target.value='';};
let dragDepth=0;window.addEventListener('dragenter',e=>{if(e.dataTransfer.types.includes('Files')){e.preventDefault();dragDepth++;$('#drag-overlay').classList.add('visible');}});window.addEventListener('dragover',e=>{e.preventDefault();});window.addEventListener('dragleave',e=>{e.preventDefault();if(--dragDepth<=0)$('#drag-overlay').classList.remove('visible');});window.addEventListener('drop',e=>{e.preventDefault();dragDepth=0;$('#drag-overlay').classList.remove('visible');importFile(e.dataTransfer.files[0]);});
$('#load-demo').onclick=()=>{if(!state.demo&&!confirm('Sostituire il modello attuale con il modello demo?'))return;loadModel('demo');};$('#reset-project').onclick=()=>{if(confirm('Iniziare un nuovo progetto? I tagli attuali verranno sostituiti dal modello demo.'))loadModel('demo');};
$('#show-planes').onchange=updatePlanes;$('#explode').onchange=()=>{updateExplosion();$('#separation').disabled=!$('#explode').checked;};$('#separation').oninput=()=>{$('#separation-value').textContent=$('#separation').value;$('#separation').style.setProperty('--pct',`${Number($('#separation').value)/70*100}%`);updateExplosion();};
$('#fit-view').onclick=()=>fitView();$('#top-view').onclick=()=>fitView(true);function setWire(wire){state.wire=wire;group.children.forEach(m=>m.material.wireframe=wire);$('#solid-view').classList.toggle('active',!wire);$('#wire-view').classList.toggle('active',wire);}$('#solid-view').onclick=()=>setWire(false);$('#wire-view').onclick=()=>setWire(true);$('#grid-view').onclick=()=>{const show=$('#grid-view').classList.toggle('active');if(grid)grid.visible=show;};

function stlBytes(part){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(part.positions.slice(),3));geometry.setIndex(new THREE.BufferAttribute(part.indices,1));const b=part.bounds;geometry.translate(-(b.min[0]+b.max[0])/2,-(b.min[1]+b.max[1])/2,-b.min[2]);const mesh=new THREE.Mesh(geometry);const output=new STLExporter().parse(mesh,{binary:true});geometry.dispose();mesh.material.dispose();return new Uint8Array(output.buffer,output.byteOffset,output.byteLength);}
function save(bytes,name,type='application/octet-stream'){const blob=new Blob([bytes],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function downloadPart(i){if(state.busy||state.dirty)return;save(stlBytes(state.parts[i]),`${safeName(state.name)}_parte_${String(i+1).padStart(2,'0')}.stl`);toast(`Parte ${String(i+1).padStart(2,'0')} esportata in STL.`);}
$('#export-all').onclick=()=>{if(state.busy||state.dirty||!state.parts.length)return;try{const files={};state.parts.forEach((p,i)=>files[`${safeName(state.name)}_parte_${String(i+1).padStart(2,'0')}.stl`]=stlBytes(p));files['LEGGIMI.txt']=strToU8(`SEZIONE — Esportazione STL\n\nModello: ${state.name}\nUnità: millimetri\nAsse di taglio: ${['X','Y','Z'][state.appliedAxis]}\nPosizioni assolute dei piani sul modello normalizzato: ${state.appliedPlanes.map(fmt).join(', ')} mm\nParti: ${state.parts.length}\n\nOgni parte è centrata in X/Y, con la base a Z = 0.\nLa distanza della vista esplosa non è inclusa negli STL.\nSuperfici di taglio chiuse; nessun incastro automatico.\nUna sezione può contenere più componenti scollegate.\nControlla scala, orientamento, supporti e dimensioni nel tuo slicer.\n\n${state.parts.map((p,i)=>`Parte ${i+1}: ${dimensions(p.bounds)} mm, ${p.triangles} triangoli`).join('\n')}\n`);save(zipSync(files,{level:3}),`${safeName(state.name)}_parti.zip`,'application/zip');toast(`${state.parts.length} parti esportate in un archivio ZIP.`);}catch(e){toast('Esportazione non riuscita. Prova a scaricare le parti singolarmente.',true);}};
const dialog=$('#guide-dialog');$('#help').onclick=$('#export-help').onclick=()=>dialog.showModal();$('#close-guide').onclick=$('#start-working').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
window.addEventListener('keydown',e=>{if(dialog.open)return;if((e.ctrlKey||e.metaKey)&&e.key==='o'){e.preventDefault();if(!state.busy)$('#file-input').click();return;}if(e.target.matches('input,textarea,button')||state.busy)return;if(e.key.toLowerCase()==='r')fitView();if(e.key.toLowerCase()==='w')setWire(!state.wire);if(e.key==='Enter'&&state.dirty)$('#apply-cuts').click();});
loadModel('demo');
